### ISSUE TITLE
[EPIC] Creating a reusable QA workflow script

### ISSUE THREAD

**Issue by jarmoza** [printprobability/qa-workflow#1]
Below are the tasks for a first stab at creating a generalized QA script for the PnP book processing and ingestion pipeline.

### QA Script Pipeline Tasks

**Master Script**
- [x] One Python script should be set up with arguments to run the various possible subprocesses of this QA process and output metadata on each QA run (time run, slurm log list for each sbatch call, etc.)
- [x] An optional config file (i.e. yaml file) that includes directories and optionally a sequence of the QA subprocesses to run (i.e. clear old results, run new QA, gather results, analyze, etc.)
See: https://github.com/printprobability/qa-workflow/issues/3

**Subprocesses**
- [x] Run test autocrop script with arguments across one or more given book directories
- [x] The ability to clear old results folders from a list of book directories  (including an 'Are you sure?' option for safety) https://github.com/printprobability/qa-workflow/issues/4
- [x] Gather output metadata into one file from all book directory 'results' from a QA run https://github.com/printprobability/qa-workflow/issues/2

**Error Processing**
- [x] Distinguishing between slurm output logs of errored and successful runs
- [ ] Bucketing errors once errored runs are identified – what and how many of each
- [ ] Analyzing errors (bridges and autocrop) and implementing fixes for them
See: https://github.com/printprobability/qa-workflow/issues/6

**Metadata Additions/Fixes**
- [X] Image dimensions and area
- [X] Area difference from crop to original
- [X] Frobenius/L2 norm from crop to original
- [x] File count for originals and for each crop run
- [x] Percent area of crop to original https://github.com/printprobability/qa-workflow/issues/7

**Asserts**
- [ ] TBD acceptable %'s for metadata differences from crop to original images
